config/routes.rb
Mastercoin::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  get "pages/home"

  root 'pages#home'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.username = auth.info.nickname
		end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"]) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
	  super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  alias_method :facebook, :all
  alias_method :google_oauth2, :all
  alias_method :reddit, :all
  alias_method :github, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>COPYRIGHT © 2013 MASTERCOIN.  ALL RIGHTS RESERVED.</p>
</div>

app/views/layouts/_header.html.erb
<div class="navbar transparent navbar-inverse navbar-fixed-top">
  <div class="navbar-inner sticky">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <%= link_to image_tag('mastercoin_logo.png'), '/', class: "brand", method: :get %>
        <div class="nav-collapse collapse">
          <ul class="nav pull-left">
          </ul>

          <ul class="nav pull-right">
            <% if admin_signed_in? %>
              <li><%= link_to "AdminLogout", destroy_admin_session_path, method: :delete %></li>
            <% elsif user_signed_in? == false %>
              <li><%= link_to 'Sign-in', '', id: "show_login_box" %></li>
            <% else user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function() {
  $("#show_login_box").on("click", function(){
    $("#show_login").slideToggle();
    return false
  });
});
</script>

app/views/layouts/_sidebar.html.erb
<div class="login_box" style="display:none" id="show_login">
  <div class="row"> 
    <div class="span3">
      <div class="well sidebar-nav">
        <h3>Mastercoin</h3>
        <div class="nav-header">
          Sign in through:
        </div>
        <ul class="nav nav-list">
          <li><%= link_to image_tag('facebook.png'), user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to image_tag('github.png'), user_omniauth_authorize_path(:github) %></li> 
          <li><%= link_to image_tag('google.png'), user_omniauth_authorize_path(:google_oauth2) %></li>
          <li><%= link_to image_tag('reddit.jpg'), user_omniauth_authorize_path(:reddit) %></li>
          <li><%= link_to image_tag('twitter.png'), user_omniauth_authorize_path(:twitter) %></li> 
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mastercoin" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <% if current_page?(root_path) %>
      <%= render 'layouts/sidebar' %>
    <% end %>

    <div id="container1">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h3>Mastercoin Faucet</h3>

<p>This website is made to award small amounts of Mastercoins to new users, in order to prevent abuse new members will have to pass a couple of criteria. </p>

<h4>Criteria:</h4>

<h5>Basic authentication</h5>
<li>Anyone that registers with a Google/Facebook account (amount given will be smaller than signing in through premium authentication). </li>

<h5>Premium authentication</h5>
<li>Anyone with a reddit account with karma above 100.</li>
<li>Anyone who's had a github account with either (at least 3 public repositories) or (stared one of the <a href="http://wiki.mastercoin.org/index.php/FAQ#Is_Mastercoin_open_source.3F" target="_blank">Mastercoin github repositories listed here</a>) and (account created before date Aug 1st 2013).</li>

<h5>Criteria that still need to be implemented</h5>

<li>Anyone who had a bitcointalk account with activity score > 10, at least 10 posts, accounts created prior to Aug 1 2013.</li>